import java.util.HashMap;
import java.util.Set;

public class Hash {
    public static void main(String[] args) {
        HashMap<String, String> songMap = new HashMap<String, String>();
        songMap.put("Saving Light",
                "I'm here. Where endless meets the end. Do you see me? I'm hidden here again. Your whisper found its way. Calling me to stay. I'm standing at the edge. But something always brings me back. All the voices in my head. Reminding me of what I have. If I fall tonight. You can bring me back to life. If I fall tonight. You can be my saving light. You can be my saving light. You can be my saving light. You can be my saving light. You're here. Like lightning in my veins. Now they see me. And they'll never be insane. Your whispers found its way. Calling me to stay. You can be my saving light. I'm standing at the edge. But something always brings me back. All the voices in my head. Reminding of what I have. If I fall tonight. You can bring me back to life. If I fall tonight. You can be my saving light. You can be my saving light. You can be my saving light. You can be my saving light. You can be my saving light");
        songMap.put("Watermelon Sugar",
                "Tastes like strawberries. On a summer evenin'. And it sounds just like a song. I want more berries. And that summer feelin'. It's so wonderful and warm. Breathe me in, breathe me out. I don't know if I could ever go without. I'm just thinking out loud. I don't know if I could ever go without. Watermelon sugar high. Watermelon sugar high. Watermelon sugar high. Watermelon sugar high. Watermelon sugar. Strawberries on a summer evenin'. Baby, you're the end of June. I want your belly. And that summer feelin'. Getting washed away in you. Breathe me in, breathe me out. I don't know if I could ever go without. Watermelon sugar high. Watermelon sugar high. Watermelon sugar high. Watermelon sugar high. Watermelon sugar high. Watermelon sugar high. Watermelon sugar high. Watermelon sugar high. I just wanna taste it, I just wanna taste it. Watermelon sugar high. Tastes like strawberries. On a summer evenin'. And it sounds just like a song. I want your belly. And that summer feelin'. I don't know if I could ever go without. Watermelon sugar high. Watermelon sugar high. Watermelon sugar high (sugar). Watermelon sugar high (sugar). Watermelon sugar high. Watermelon sugar high. Watermelon sugar high. Watermelon sugar high. I just wanna taste it, I just wanna taste it. Watermelon sugar high. I just wanna taste it, I just wanna taste it. Watermelon sugar high. Watermelon sugar");
        songMap.put("Blinding Lights",
                "I've been tryin' to call. I've been on my own for long enough. Maybe you can show me how to love, maybe. I'm going through withdrawals. You don't even have to do too much. You can turn me on with just a touch, baby. I look around and. Sin City's cold and empty (oh). No one's around to judge me (oh). I can't see clearly when you're gone. I said, ooh, I'm blinded by the lights. No, I can't sleep until I feel your touch. I said, ooh, I'm drowning in the night. Oh, when I'm like this, you're the one I trust. Hey, hey, hey. I'm running out of time. 'Cause I can see the sun light up the sky. So I hit the road in overdrive, baby, oh. The city's cold and empty (oh). No one's around to judge me (oh). I can't see clearly when you're gone. I said, ooh, I'm blinded by the lights. No, I can't sleep until I feel your touch. I said, ooh, I'm drowning in the night. Oh, when I'm like this, you're the one I trust. I'm just walking by to let you know (by to let you know). I could never say it on the phone (say it on the phone). Will never let you go this time (ooh). I said, ooh, I'm blinded by the lights. No, I can't sleep until I feel your touch. Hey, hey, hey. Hey, hey, hey. I said, ooh, I'm blinded by the lights. No, I can't sleep until I feel your touch");
        songMap.put("Some one like you",
                "I heard that you're settled down. That you found a girl and you're married now. I heard that your dreams came true. Guess she gave you things I didn't give to you. Old friend, why are you so shy? Ain't like you to hold back or hide from the light. I hate to turn up out of the blue uninvited. But I couldn't stay away, I couldn't fight it. I had hoped you'd see my face and that you'd be reminded. That for me it isn't over. Never mind, I'll find someone like you. I wish nothing but the best for you too. Don't forget me, I beg. I'll remember you said, Sometimes it lasts in love but sometimes it hurts instead, Sometimes it lasts in love but sometimes it hurts instead. You know how the time flies. Only yesterday was the time of our lives. We were born and raised. In a summer haze. Bound by the surprise of our glory days. I hate to turn up out of the blue uninvited. But I couldn't stay away, I couldn't fight it. I'd hoped you'd see my face and that you'd be reminded. That for me it isn't over. Never mind, I'll find someone like you. I wish nothing but the best for you too. Don't forget me, I beg. I'll remember you said, Sometimes it lasts in love but sometimes it hurts instead.. Nothing compares. No worries or cares. Regrets and mistakes. They are memories made. Who would have known how bittersweet this would taste? Never mind, I'll find someone like you. I wish nothing but the best for you. Don't forget me, I beg. I'll remember you said, Sometimes it lasts in love but sometimes it hurts instead. Never mind, I'll find someone like you. I wish nothing but the best for you too. Don't forget me, I beg. I'll remember you said, Sometimes it lasts in love but sometimes it hurts instead, Sometimes it lasts in love but sometimes it hurts instead.");
        Set<String> tracks = songMap.keySet();
        for (String track : tracks) {
            System.out.println(String.format("%s : %s", track, songMap.get(track)));
        }
    }
}
